const CONFIG={
 password:'1010',name:'Nia Ramadani',birthdayDate:'2026-10-10T00:00:00',music:'assets/music/song.mp3',
 heroText:'Hari ini, babak indah yang baru dimulai untukmu, sayang. ❤️ Semoga hari-harimu selalu dipenuhi alasan kecil untuk tersenyum, momen tenang untuk beristirahat dari lelahnya dunia, dan banyak hal indah yang bisa kamu nantikan. Semoga kebahagiaan selalu menemukan jalannya kepadamu, dan semoga kamu selalu ingat betapa berharganya dirimu. Aku berharap hari-hari ke depan akan membawa lebih banyak senyum, cinta, dan kebahagiaan untukmu. 🤍',
 message:`Happy Birthday, Nia Ramadani ❤️\n\nHari ini bukan cuma tentang angka yang bertambah. Hari ini adalah pengingat bahwa dunia pernah menjadi sedikit lebih indah ketika seseorang seperti kamu hadir di dalamnya.\n\nSemoga langkahmu selalu menemukan jalan yang baik. Semoga hal-hal yang kamu doakan perlahan datang satu per satu. Dan ketika hari sedang tidak mudah, semoga kamu tetap punya alasan kecil untuk tersenyum.\n\nTeruslah menjadi dirimu sendiri. Tetap hangat, tetap kuat, dan jangan lupa bahwa kamu pantas mendapatkan banyak hal baik.\n\nSelamat membuka chapter baru. Semoga chapter ini menjadi salah satu yang paling indah. ✨`,
 gallery:Array.from({length:12},(_,i)=>({src:`assets/images/Nia${String(i+1).padStart(1,'1')}.jpeg`,caption:["A beautiful little moment","A memory worth keeping","One of many smiles","A day to remember","Soft moments, happy hearts","Another chapter","Little things we keep","A favorite frame","A quiet happy day","One more reason to smile","A memory in bloom","Forever worth remembering"][i]})),
 reasons:[['Senyummu ❤️','Karena entah bagaimana, senyummu selalu bisa membuat momen sederhana terasa lebih hangat dan istimewa.'],['Kebaikan Hatimu 🤍','Hal-hal kecil yang kamu lakukan untuk orang lain mungkin terlihat sederhana bagimu, tapi sebenarnya sangat berarti. Kamu punya hati yang baik, dan itu salah satu hal yang membuatku kagum padamu.'],['Energi yang Kamu Bawa ✨','Kamu punya cara tersendiri untuk membawa kehangatan dan kebahagiaan. Kehadiranmu membuat suasana terasa berbeda, dan tidak ada yang bisa menggantikan caramu membuat hari-hariku lebih berwarna.'],['Hatimu yang Tulus 🌷','Di tengah dunia yang terkadang melelahkan, kamu punya hati yang lembut dan tulus. Bagiku, itu adalah sesuatu yang sangat berharga dan istimewa.'],['Mimpi-Mimpimu 🌙','Jangan pernah berhenti mengejar hal-hal yang membuat matamu berbinar. Aku berharap kamu selalu berani meraih apa yang kamu impikan, dan aku ingin melihatmu tumbuh, bahagia, serta bangga pada dirimu sendiri'],['Dirimu, Apa Adanya 💗','Kamu nggak perlu menjadi orang lain untuk pantas mendapatkan hal-hal indah. Kamu sudah istimewa dengan menjadi dirimu sendiri, dan semoga kamu selalu ingat betapa berharganya dirimu.']],
timeline: [
    [
        '2023',
        'Awal dari Sebuah Cerita',
        'Terkadang, momen kecil menjadi awal dari sesuatu yang indah. Aku tidak pernah menyangka bahwa kamu akan menjadi seseorang yang begitu istimewa dalam hidupku.',
        'assets/images/fotbar (1).jpeg'
    ],
    [
        '2024',
        'Momen Kecil, Arti yang Besar',
        'Setiap tawa, percakapan sederhana, dan waktu yang kita habiskan bersama menjadi kenangan yang tidak ingin aku lupakan.',
        'assets/images/fotbar (4).jpeg'
    ],
    [
        '2025',
        'Tumbuh Bersama',
        'Di setiap hari yang penuh kebahagiaan maupun kesulitan, aku berharap kita bisa terus belajar, tumbuh bersama, dan menemukan lebih banyak alasan untuk tetap memilih satu sama lain.',
        'assets/images/fotbar (3).jpeg'
    ],
    [
        '2026',
        'Cerita Favoritku Adalah Kamu',
        'Jika hidup adalah sebuah buku, aku berharap masih ada banyak halaman indah yang bisa kita tulis bersama. Dan jika diberi kesempatan untuk memilih lagi, aku tetap bahagia karena bisa menjadikanmu bagian dari ceritaku.',
        'assets/images/fotbar (2).jpeg'
    ]
],
 wishes:['Semoga semua impianmu menemukan jalannya. ✨','Semoga kamu selalu dikelilingi orang-orang yang tulus menyayangimu. ❤️','Semoga tahun ini memberimu lebih banyak alasan untuk tersenyum.','Semoga hatimu selalu punya tempat untuk tenang.','Semoga setiap langkahmu bertemu dengan hal-hal baik.','Semoga kamu selalu ingat betapa berharganya dirimu. ♡']
};
const $=id=>document.getElementById(id); let current=0,wishCount=Number(localStorage.getItem('birthdayWishCount')||0),typing;
function init(){document.title=`Happy Birthday, ${CONFIG.name} ♡`;$('name1').textContent=CONFIG.name;$('name2').textContent=CONFIG.name;$('heroText').textContent=CONFIG.heroText;$('audio').src=CONFIG.music;$('audio').volume=.42;renderReasons();renderGallery();renderTimeline();renderWishes();$('wishCount').textContent=wishCount;countdown();observe();}
window.addEventListener('load',()=>{init();setTimeout(()=>$('loader').classList.add('hide'),1100);setTimeout(()=>$('password').focus(),1250);});
$('passwordForm').addEventListener('submit',e=>{e.preventDefault();if($('password').value.trim()===CONFIG.password){$('passMsg').textContent='';unlock()}else{$('passMsg').textContent='Oops, passwordnya salah ❤️';$('password').animate([{transform:'translateX(0)'},{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'translateX(0)'}],{duration:300})}});
$('showPass').onclick=()=>{$('password').type=$('password').type==='password'?'text':'password';};
async function unlock(){$('lock').classList.add('out');$('site').classList.add('show');$('site').setAttribute('aria-hidden','false');document.body.classList.remove('locked');hearts(22);confetti(75);try{await $('audio').play();musicUI(true)}catch{musicUI(false)}setTimeout(()=>{$('lock').style.display='none';typeMessage();observe()},850)}
function musicUI(on){$('musicBtn').classList.toggle('playing',on);$('musicText').textContent=on?'PLAYING':'MUSIC';$('musicBtn').textContent=on?'❚❚':'♫';let s=document.createElement('small');s.id='musicText';s.textContent=on?'PLAYING':'MUSIC';$('musicBtn').appendChild(s)}
$('musicBtn').onclick=async()=>{if($('audio').paused){try{await $('audio').play();musicUI(true)}catch{$('musicText').textContent='ADD MP3'}}else{$('audio').pause();musicUI(false)}};
$('menuBtn').onclick=()=>{$('navMenu').classList.toggle('open')};document.querySelectorAll('.nav-menu a').forEach(a=>a.onclick=()=> $('navMenu').classList.remove('open'));
function typeMessage(){clearInterval(typing);$('typed').textContent='';let i=0;typing=setInterval(()=>{ $('typed').textContent=CONFIG.message.slice(0,i++);if(i>CONFIG.message.length)clearInterval(typing)},10)}$('again').onclick=typeMessage;
function renderReasons(){$('reasonsGrid').innerHTML=CONFIG.reasons.map((r,i)=>`<article class="reason-card reveal"><div class="reason-inner"><button class="face front"><b>0${i+1}</b><strong>${r[0]}</strong><small>tap to reveal ♡</small></button><button class="face back"><p>${r[1]}</p></button></div></article>`).join('');document.querySelectorAll('.reason-card').forEach(c=>c.querySelectorAll('button').forEach(b=>b.onclick=()=>c.classList.toggle('flip')));observe()}
function renderGallery(){$('thumbs').innerHTML=CONFIG.gallery.map((g,i)=>`<button class="thumb ${i?'':'active'}" data-i="${i}"><img src="${g[0]}" alt=""></button>`).join('');document.querySelectorAll('.thumb').forEach(t=>t.onclick=()=>setPhoto(+t.dataset.i));$('featureImg').onclick=()=>openLight(current);$('prev').onclick=()=>setPhoto(current-1);$('next').onclick=()=>setPhoto(current+1);setPhoto(0)}
function setPhoto(i){current=(i+CONFIG.gallery.length)%CONFIG.gallery.length;let g=CONFIG.gallery[current];$('featureImg').src=g[0];$('photoNo').textContent=`${String(current+1).padStart(2,'0')} / 06`;$('photoCap').textContent=g[1];document.querySelectorAll('.thumb').forEach((t,j)=>t.classList.toggle('active',j===current));$('featureImg').animate([{opacity:.35,transform:'scale(.985)'},{opacity:1,transform:'scale(1)'}],{duration:320})}
function renderTimeline(){$('timeline').innerHTML=CONFIG.timeline.map(t=>`<article class="time-item reveal"><span class="node"></span><div class="copy"><span class="year">${t[0]}</span><h4>${t[1]}</h4><p>${t[2]}</p></div><div class="photo"><img src="${t[3]}" alt="${t[1]}"></div></article>`).join('');observe()}
function renderWishes(){$('wishGrid').innerHTML=CONFIG.wishes.map(w=>`<article class="wish-card reveal"><strong>${w}</strong></article>`).join('');observe()}$('randomWish').onclick=()=>{$('randomText').textContent=CONFIG.wishes[Math.floor(Math.random()*CONFIG.wishes.length)];};
$('candle').onclick=()=>{if($('candle').classList.contains('out'))return;$('candle').classList.add('out');wishCount++;localStorage.setItem('birthdayWishCount',wishCount);$('wishCount').textContent=wishCount;$('cakeMsg').textContent='Your wish has been sent to the stars ✨';confetti(60);hearts(18)};
$('finalWish').onclick=()=>{wishCount++;localStorage.setItem('birthdayWishCount',wishCount);$('wishCount').textContent=wishCount;$('result').textContent='Your wish has been sent to the universe ✨';confetti(120);hearts(28)};
$('gift').onclick=()=>{$('gift').classList.add('open');$('secret').classList.add('show');confetti(45);hearts(12)};
function openLight(i){current=i;$('lightImg').src=CONFIG.gallery[current][0];$('lightCap').textContent=CONFIG.gallery[current][1];$('lightbox').classList.add('open');document.body.classList.add('locked')}$('closeLight').onclick=closeLight;$('lightbox').onclick=e=>{if(e.target.id==='lightbox')closeLight()};$('lightPrev').onclick=()=>{setPhoto(current-1);openLight(current)};$('lightNext').onclick=()=>{setPhoto(current+1);openLight(current)};function closeLight(){$('lightbox').classList.remove('open');document.body.classList.remove('locked')}
document.onkeydown=e=>{if($('lightbox').classList.contains('open')){if(e.key==='Escape')closeLight();if(e.key==='ArrowLeft')$('lightPrev').click();if(e.key==='ArrowRight')$('lightNext').click()}};
function countdown(){let target=new Date(CONFIG.birthdayDate).getTime();function t(){let x=Math.max(0,target-Date.now());$('d').textContent=String(Math.floor(x/86400000)).padStart(2,'0');$('h').textContent=String(Math.floor(x/3600000)%24).padStart(2,'0');$('m').textContent=String(Math.floor(x/60000)%60).padStart(2,'0');$('s').textContent=String(Math.floor(x/1000)%60).padStart(2,'0')}t();setInterval(t,1000)}
let observer;function observe(){if(!observer)observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not([data-r])').forEach(x=>{x.dataset.r='1';observer.observe(x)})}
function hearts(n){for(let i=0;i<n;i++){let h=document.createElement('span');h.className='heart';h.textContent=['♡','♥','✦','✧'][i%4];h.style.left=Math.random()*100+'%';h.style.fontSize=.7+Math.random()*1.2+'rem';h.style.setProperty('--t',4+Math.random()*5+'s');$('hearts').appendChild(h);setTimeout(()=>h.remove(),10000)}}
function confetti(n){let colors=['#d98193','#c5a36b','#fff','#c991a0'];for(let i=0;i<n;i++){let c=document.createElement('span');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.background=colors[i%4];c.style.setProperty('--d',2.6+Math.random()*2.7+'s');$('confetti').appendChild(c);setTimeout(()=>c.remove(),5600)}}
let last=0;document.addEventListener('pointermove',e=>{if(innerWidth<900)return;$('cursorGlow').style.left=e.clientX+'px';$('cursorGlow').style.top=e.clientY+'px';let now=Date.now();if(now-last<70)return;last=now;let s=document.createElement('span');s.className='spark';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';$('sparkleLayer').appendChild(s);setTimeout(()=>s.remove(),700)});
document.addEventListener('dblclick',e=>{if(e.target.closest('a,button,input'))return;hearts(8)});

function renderGallery(){const t=$("thumbs"),grid=$("photoGrid");t.innerHTML=CONFIG.gallery.map((g,i)=>`<button class="thumb ${i===0?'active':''}" data-i="${i}"><img src="${g.src}" alt="${g.caption}"></button>`).join('');grid.innerHTML=CONFIG.gallery.map((g,i)=>`<button class="photo-card reveal" data-i="${i}"><img src="${g.src}" alt="${g.caption}"><span>${String(i+1).padStart(2,'0')} · ${g.caption}</span></button>`).join('');$("galleryTotal").textContent=CONFIG.gallery.length;$("photoCaption").textContent=CONFIG.gallery[0].caption;t.querySelectorAll('.thumb').forEach(x=>x.addEventListener('click',()=>setPhoto(Number(x.dataset.i))));grid.querySelectorAll('.photo-card').forEach(x=>x.addEventListener('click',()=>openLight(Number(x.dataset.i))));$("feature").addEventListener('click',()=>openLight(current));$("prev").addEventListener('click',()=>setPhoto(current-1));$("next").addEventListener('click',()=>setPhoto(current+1));$("feature").addEventListener('touchstart',e=>window._touch=e.changedTouches[0].clientX,{passive:true});$("feature").addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-window._touch;if(Math.abs(d)>45)setPhoto(current+(d<0?1:-1))});observe();observe()}
function setPhoto(i){current=(i+CONFIG.gallery.length)%CONFIG.gallery.length;let g=CONFIG.gallery[current],im=$("feature");im.animate([{opacity:.35,transform:'scale(.985)'},{opacity:1,transform:'scale(1)'}],{duration:300});im.src=g.src;im.alt=g.caption;$("photoNum").textContent=String(current+1).padStart(2,'0');$("photoCaption").textContent=g.caption;$("galleryShown").textContent=current+1;document.querySelectorAll('.thumb').forEach((t,k)=>t.classList.toggle('active',k===current))}
function openLight(i){current=(i+CONFIG.gallery.length)%CONFIG.gallery.length;updateLight();$("lightbox").classList.add('open');document.body.classList.add('locked')}function updateLight(){let g=CONFIG.gallery[current];$("lightImg").src=g.src;$("lightCap").textContent=g.caption}function closeLight(){$("lightbox").classList.remove('open');document.body.classList.remove('locked')}$("closeLight").addEventListener('click',closeLight);$("lightPrev").addEventListener('click',()=>{current=(current-1+CONFIG.gallery.length)%CONFIG.gallery.length;updateLight();setPhoto(current)});$("lightNext").addEventListener('click',()=>{current=(current+1)%CONFIG.gallery.length;updateLight();setPhoto(current)});$("lightbox").addEventListener('click',e=>{if(e.target.id==='lightbox')closeLight()});document.addEventListener('keydown',e=>{if(!$('lightbox').classList.contains('open'))return;if(e.key==='Escape')closeLight();if(e.key==='ArrowLeft')$('lightPrev').click();if(e.key==='ArrowRight')$('lightNext').click()});
