const CONFIG={
 password:'1010',name:'Nama Dia',birthdayDate:'2026-10-02T23:59:59',music:'assets/music/song.mp3',
 heroText:'Another beautiful chapter begins today. May your days be filled with little reasons to smile, quiet moments to breathe, and beautiful things to look forward to.',
 message:`Happy Birthday, Nama Dia ❤️\n\nHari ini bukan cuma tentang angka yang bertambah. Hari ini adalah pengingat bahwa dunia pernah menjadi sedikit lebih indah ketika seseorang seperti kamu hadir di dalamnya.\n\nSemoga langkahmu selalu menemukan jalan yang baik. Semoga hal-hal yang kamu doakan perlahan datang satu per satu. Dan ketika hari sedang tidak mudah, semoga kamu tetap punya alasan kecil untuk tersenyum.\n\nTeruslah menjadi dirimu sendiri. Tetap hangat, tetap kuat, dan jangan lupa bahwa kamu pantas mendapatkan banyak hal baik.\n\nSelamat membuka chapter baru. Semoga chapter ini menjadi salah satu yang paling indah. ✨`,
 gallery:[
  ['assets/images/photo1.jpg','A beautiful little moment'],['assets/images/photo2.jpg','A memory worth keeping'],['assets/images/photo3.jpg','One of many smiles'],['assets/images/photo4.jpg','Another chapter, another memory'],['assets/images/photo5.jpg','Soft moments, happy hearts'],['assets/images/photo6.jpg','A day to remember']],
 reasons:[['Your Smile','Because somehow your smile can make ordinary moments feel a little warmer.'],['Your Kindness','The small things you do for people matter more than you probably realize.'],['Your Energy','You bring a certain kind of warmth that is difficult to replace.'],['Your Heart','A soft heart in a busy world is something very special.'],['Your Dreams','Never stop chasing the things that make your eyes light up.'],['Simply You','You do not have to become someone else to be worthy of beautiful things.']],
 timeline:[['2023','A Little Beginning','Every story starts with a small moment. Some of them quietly become unforgettable.','assets/images/photo2.jpg'],['2024','More Reasons To Smile','New places, new stories, and moments that found a permanent place in the heart.','assets/images/photo3.jpg'],['2025','Growing & Glowing','Another year of learning, laughing, growing, and becoming more of yourself.','assets/images/photo5.jpg'],['2026','A Brand New Chapter','A new page is waiting. May it be soft, brave, bright, and full of good surprises.','assets/images/photo6.jpg']],
 wishes:['Semoga semua impianmu menemukan jalannya. ✨','Semoga kamu selalu dikelilingi orang-orang yang tulus menyayangimu. ❤️','Semoga tahun ini memberimu lebih banyak alasan untuk tersenyum.','Semoga hatimu selalu punya tempat untuk tenang.','Semoga setiap langkahmu bertemu dengan hal-hal baik.','Semoga kamu selalu ingat betapa berharganya dirimu. ♡']
};
const $=id=>document.getElementById(id); let current=0,wishCount=Number(localStorage.getItem('birthdayWishCount')||0),typing;
function init(){document.title=`Happy Birthday, ${CONFIG.name} ♡`;$('name1').textContent=CONFIG.name;$('name2').textContent=CONFIG.name;$('heroText').textContent=CONFIG.heroText;$('audio').src=CONFIG.music;$('audio').volume=.42;renderReasons();renderGallery();renderTimeline();renderWishes();$('wishCount').textContent=wishCount;countdown();observe();}
window.addEventListener('load',()=>{init();setTimeout(()=>$('loader').classList.add('hide'),1100);setTimeout(()=>$('password').focus(),1250);});
$('passwordForm').addEventListener('submit',e=>{e.preventDefault();if($('password').value.trim()===CONFIG.password){$('passMsg').textContent='';unlock()}else{$('passMsg').textContent='Oops, passwordnya salah ❤️';$('password').animate([{transform:'translateX(0)'},{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'translateX(0)'}],{duration:300})}});
$('showPass').onclick=()=>{$('password').type=$('password').type==='password'?'text':'password';};
async function unlock(){$('lock').classList.add('out');$('site').classList.add('show');$('site').setAttribute('aria-hidden','false');document.body.classList.remove('locked');hearts(22);confetti(75);try{await $('audio').play();musicUI(true)}catch{musicUI(false)}setTimeout(()=>{$('lock').style.display='none';typeMessage();observe()},850)}
function musicUI(on){$('musicBtn').classList.toggle('playing',on);$('musicText').textContent=on?'PLAYING':'MUSIC';$('musicBtn').textContent=on?'❚❚':'♫';let s=document.createElement('small');s.id='musicText';s.textContent=on?'PLAYING':'MUSIC';$('musicBtn').appendChild(s)}
$('musicBtn').onclick=async()=>{if($('audio').paused){try{await $('audio').play();musicUI(true)}catch{$('musicText').textContent='ADD MP3'}}else{$('audio').pause();musicUI(false)}};
$('menuBtn').onclick=()=>{$('navMenu').classList.toggle('open')};document.querySelectorAll('.nav-menu a').forEach(a=>a.onclick=()=> $('navMenu').classList.remove('open'));
$('moreBtn').onclick=()=>$('gallery').scrollIntoView({behavior:'smooth'});
function typeMessage(){clearInterval(typing);$('typed').textContent='';let i=0;typing=setInterval(()=>{ $('typed').textContent=CONFIG.message.slice(0,i++);if(i>CONFIG.message.length)clearInterval(typing)},10)}$('again').onclick=typeMessage;
function renderReasons(){$('reasonsGrid').innerHTML=CONFIG.reasons.map((r,i)=>`<article class="reason-card reveal"><div class="reason-inner"><button class="face front"><b>0${i+1}</b><strong>${r[0]}</strong><small>tap to reveal ♡</small></button><button class="face back"><p>${r[1]}</p></button></div></article>`).join('');document.querySelectorAll('.reason-card').forEach(c=>c.querySelectorAll('button').forEach(b=>b.onclick=()=>c.classList.toggle('flip')));observe()}
function renderGallery(){$('thumbs').innerHTML=CONFIG.gallery.map((g,i)=>`<button class="thumb ${i?'':'active'}" data-i="${i}"><img src="${g[0]}" alt=""></button>`).join('');document.querySelectorAll('.thumb').forEach(t=>t.onclick=()=>setPhoto(+t.dataset.i));$('featureImg').onclick=()=>openLight(current);$('prev').onclick=()=>setPhoto(current-1);$('next').onclick=()=>setPhoto(current+1);setPhoto(0)}
function setPhoto(i){current=(i+CONFIG.gallery.length)%CONFIG.gallery.length;let g=CONFIG.gallery[current];$('featureImg').src=g[0];$('photoNo').textContent=`${String(current+1).padStart(2,'0')} / 06`;$('photoCap').textContent=g[1];document.querySelectorAll('.thumb').forEach((t,j)=>t.classList.toggle('active',j===current));$('featureImg').animate([{opacity:.35,transform:'scale(.985)'},{opacity:1,transform:'scale(1)'}],{duration:320})}
let tx=0;$('featureImg').ontouchstart=e=>tx=e.changedTouches[0].clientX;$('featureImg').ontouchend=e=>{let d=e.changedTouches[0].clientX-tx;if(Math.abs(d)>45)setPhoto(current+(d<0?1:-1))};
function renderTimeline(){$('timeline').innerHTML=CONFIG.timeline.map(t=>`<article class="time-item reveal"><span class="node"></span><div class="copy"><span class="year">${t[0]}</span><h4>${t[1]}</h4><p>${t[2]}</p></div><div class="photo"><img src="${t[3]}" alt="${t[1]}"></div></article>`).join('');observe()}
function renderWishes(){$('wishGrid').innerHTML=CONFIG.wishes.map(w=>`<article class="wish-card reveal"><strong>${w}</strong></article>`).join('');observe()}$('randomWish').onclick=()=>{$('randomText').textContent=CONFIG.wishes[Math.floor(Math.random()*CONFIG.wishes.length)];};
$('candle').onclick=()=>{if($('candle').classList.contains('out'))return;$('candle').classList.add('out');wishCount++;localStorage.setItem('birthdayWishCount',wishCount);$('wishCount').textContent=wishCount;$('cakeMsg').textContent='Your wish has been sent to the stars ✨';confetti(60);hearts(18)};
$('finalWish').onclick=()=>{wishCount++;localStorage.setItem('birthdayWishCount',wishCount);$('wishCount').textContent=wishCount;$('result').textContent='Your wish has been sent to the universe ✨';confetti(120);hearts(28)};
$('gift').onclick=()=>{$('gift').classList.add('open');$('secret').classList.add('show');confetti(45);hearts(12)};
function openLight(i){current=i;$('lightImg').src=CONFIG.gallery[current][0];$('lightCap').textContent=CONFIG.gallery[current][1];$('lightbox').classList.add('open');document.body.classList.add('locked')}$('closeLight').onclick=closeLight;$('lightbox').onclick=e=>{if(e.target.id==='lightbox')closeLight()};$('lightPrev').onclick=()=>{setPhoto(current-1);openLight(current)};$('lightNext').onclick=()=>{setPhoto(current+1);openLight(current)};function closeLight(){$('lightbox').classList.remove('open');document.body.classList.remove('locked')}
document.onkeydown=e=>{if($('lightbox').classList.contains('open')){if(e.key==='Escape')closeLight();if(e.key==='ArrowLeft')$('lightPrev').click();if(e.key==='ArrowRight')$('lightNext').click()}};
function countdown(){let target=new Date(CONFIG.birthdayDate).getTime();function t(){let x=Math.max(0,target-Date.now());$('d').textContent=String(Math.floor(x/86400000)).padStart(2,'0');$('h').textContent=String(Math.floor(x/3600000)%24).padStart(2,'0');$('m').textContent=String(Math.floor(x/60000)%60).padStart(2,'0');$('s').textContent=String(Math.floor(x/1000)%60).padStart(2,'0')}t();setInterval(t,1000)}
let observer;function observe(){if(!observer)observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not([data-r])').forEach(x=>{x.dataset.r='1';observer.observe(x)})}
function hearts(n){for(let i=0;i<n;i++){let h=document.createElement('span');h.className='heart';h.textContent=['♡','♥','✦','✧'][i%4];h.style.left=Math.random()*100+'%';h.style.fontSize=.7+Math.random()*1.2+'rem';h.style.setProperty('--t',4+Math.random()*5+'s');$('hearts').appendChild(h);setTimeout(()=>h.remove(),10000)}}
function confetti(n){let colors=['#d98193','#c5a36b','#fff','#c991a0'];for(let i=0;i<n;i++){let c=document.createElement('span');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.background=colors[i%4];c.style.setProperty('--d',2.6+Math.random()*2.7+'s');$('confetti').appendChild(c);setTimeout(()=>c.remove(),5600)}}
let last=0;document.addEventListener('pointermove',e=>{if(innerWidth<900)return;$('cursorGlow').style.left=e.clientX+'px';$('cursorGlow').style.top=e.clientY+'px';let now=Date.now();if(now-last<70)return;last=now;let s=document.createElement('span');s.className='spark';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';$('sparkleLayer').appendChild(s);setTimeout(()=>s.remove(),700)});
document.addEventListener('dblclick',e=>{if(e.target.closest('a,button,input'))return;hearts(8)});
